import 'package:flutter/material.dart';

/// يحوّل اسم أيقونة نصي (مثل 'home' أو 'check_circle') إلى Icon فعلي
/// من مجموعة Material Icons. إن لم يوجد الاسم، يعرض أيقونة بديلة
/// بدل أن يتعطّل التطبيق.
class CustomIconWidget extends StatelessWidget {
  final String iconName;
  final double size;
  final Color? color;

  const CustomIconWidget({
    Key? key,
    required this.iconName,
    this.size = 24,
    this.color,
  }) : super(key: key);

  static const Map<String, IconData> _iconMap = {
    'account_balance': Icons.account_balance,
    'account_balance_wallet': Icons.account_balance_wallet,
    'account_circle': Icons.account_circle,
    'ac_unit': Icons.ac_unit,
    'add': Icons.add,
    'add_a_photo': Icons.add_a_photo,
    'add_circle': Icons.add_circle,
    'add_circle_outline': Icons.add_circle_outline,
    'add_photo_alternate': Icons.add_photo_alternate,
    'alarm': Icons.alarm,
    'apps': Icons.apps,
    'arrow_back': Icons.arrow_back,
    'arrow_back_ios': Icons.arrow_back_ios,
    'arrow_back_ios_new': Icons.arrow_back_ios_new,
    'arrow_forward': Icons.arrow_forward,
    'arrow_forward_ios': Icons.arrow_forward_ios,
    'attach_money': Icons.attach_money,
    'bar_chart': Icons.bar_chart,
    'business': Icons.business,
    'cake': Icons.cake,
    'calendar_month': Icons.calendar_month,
    'calendar_today': Icons.calendar_today,
    'call': Icons.call,
    'card_giftcard': Icons.card_giftcard,
    'cancel': Icons.cancel,
    'category': Icons.category,
    'celebration': Icons.celebration,
    'check': Icons.check,
    'check_box_outline_blank': Icons.check_box_outline_blank,
    'check_circle': Icons.check_circle,
    'check_circle_outline': Icons.check_circle_outline,
    'checkroom': Icons.checkroom,
    'chevron_left': Icons.chevron_left,
    'chevron_right': Icons.chevron_right,
    'clear': Icons.clear,
    'close': Icons.close,
    'close_fullscreen': Icons.close_fullscreen,
    'cloud_upload': Icons.cloud_upload,
    'dashboard': Icons.dashboard,
    'date_range': Icons.date_range,
    'delete': Icons.delete,
    'delete_outline': Icons.delete_outline,
    'directions': Icons.directions,
    'directions_car': Icons.directions_car,
    'download': Icons.download,
    'edit': Icons.edit,
    'email': Icons.email,
    'error': Icons.error,
    'error_outline': Icons.error_outline,
    'event': Icons.event,
    'event_available': Icons.event_available,
    'event_busy': Icons.event_busy,
    'event_note': Icons.event_note,
    'expand_less': Icons.expand_less,
    'expand_more': Icons.expand_more,
    'favorite': Icons.favorite,
    'favorite_border': Icons.favorite_border,
    'filter_list': Icons.filter_list,
    'help_outline': Icons.help_outline,
    'history': Icons.history,
    'home': Icons.home,
    'image': Icons.image,
    'image_outlined': Icons.image_outlined,
    'inbox': Icons.inbox,
    'info': Icons.info,
    'info_outline': Icons.info_outline,
    'kitchen': Icons.kitchen,
    'keyboard_arrow_down': Icons.keyboard_arrow_down,
    'keyboard_arrow_left': Icons.keyboard_arrow_left,
    'keyboard_arrow_right': Icons.keyboard_arrow_right,
    'keyboard_arrow_up': Icons.keyboard_arrow_up,
    'language': Icons.language,
    'lightbulb': Icons.lightbulb,
    'link': Icons.link,
    'local_atm': Icons.local_atm,
    'local_florist': Icons.local_florist,
    'local_parking': Icons.local_parking,
    'location_on': Icons.location_on,
    'lock': Icons.lock,
    'logout': Icons.logout,
    'map': Icons.map,
    'message': Icons.message,
    'music_note': Icons.music_note,
    'password': Icons.password,
    'payment': Icons.payment,
    'people': Icons.people,
    'person': Icons.person,
    'phone': Icons.phone,
    'phone_callback': Icons.phone_callback,
    'photo_camera': Icons.photo_camera,
    'photo_library': Icons.photo_library,
    'power': Icons.power,
    'price_check': Icons.price_check,
    'radio_button_checked': Icons.radio_button_checked,
    'rate_review': Icons.rate_review,
    'receipt_long': Icons.receipt_long,
    'refresh': Icons.refresh,
    'remove': Icons.remove,
    'report_problem': Icons.report_problem,
    'request_quote': Icons.request_quote,
    'restaurant': Icons.restaurant,
    'save': Icons.save,
    'search': Icons.search,
    'security': Icons.security,
    'send': Icons.send,
    'settings': Icons.settings,
    'share': Icons.share,
    'shopping_bag': Icons.shopping_bag,
    'spa': Icons.spa,
    'star': Icons.star,
    'star_border': Icons.star_border,
    'star_rate': Icons.star_rate,
    'storefront': Icons.storefront,
    'thumb_up': Icons.thumb_up,
    'verified': Icons.verified,
    'visibility': Icons.visibility,
    'volume_up': Icons.volume_up,
    'warning': Icons.warning,
    'wifi': Icons.wifi,
  };

  @override
  Widget build(BuildContext context) {
    final icon = _iconMap[iconName];
    if (icon != null) {
      return Icon(icon, size: size, color: color, semanticLabel: iconName);
    }
    return Icon(Icons.help_outline, size: size, color: color ?? Colors.grey, semanticLabel: iconName);
  }
}
